# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-26 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('keys', models.TextField(blank=True, help_text=b'\xe5\x8f\xaf\xe9\x85\x8d\xe7\xbd\xae\xe5\xa4\x9a\xe4\xb8\xaa,\xe6\xaf\x8f\xe4\xb8\xaa\xe4\xb8\x80\xe8\xa1\x8c,\xe7\x95\x99\xe7\xa9\xba\xe8\xa1\xa8\xe7\xa4\xba\xe4\xb8\x8d\xe9\x9c\x80\xe8\xa6\x81\xe5\xaf\x86\xe9\x92\xa5\xe5\xb0\xb1\xe5\x8f\xaf\xe6\x9f\xa5\xe7\x9c\x8b', verbose_name=b'\xe6\x9f\xa5\xe7\x9c\x8b\xe5\xaf\x86\xe9\x92\xa5')),
                ('language', models.CharField(blank=True, default=b'python', max_length=100, verbose_name=b'\xe8\x84\x9a\xe6\x9c\xac\xe8\xaf\xad\xe8\xa8\x80')),
                ('content', models.TextField(blank=True, default=b"EXAMPLE_KEY = 'ABC'", verbose_name=b'\xe8\x84\x9a\xe6\x9c\xac\xe5\x86\x85\xe5\xae\xb9')),
            ],
            options={
                'verbose_name': '\u914d\u7f6e\u811a\u672c',
                'verbose_name_plural': '\u914d\u7f6e\u811a\u672c',
            },
        ),
    ]
